version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '06:00'
      timezone: Africa/Addis_Ababa
    open-pull-requests-limit: 5
    groups:
      development-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '06:30'
      timezone: Africa/Addis_Ababa
    open-pull-requests-limit: 5
